### ISSUE TITLE
Build failed for new 0.6.0 release

### ISSUE THREAD

**Issue by julienherrero** [theGlenn/flipper-android-no-op#15]
Hi @theGlenn , the [last release ](https://jitpack.io/com/github/theGlenn/flipper-android-no-op/0.6.0/build.log)is unfortunately not working

```> Task :flipperandroidnoop:compileDebugKotlin FAILED
e: /home/jitpack/build/flipperandroidnoop/src/main/java/com/facebook/flipper/plugins/databases/DatabasesFlipperPlugin.kt: (14, 5): 'onConnect' overrides nothing
e: /home/jitpack/build/flipperandroidnoop/src/main/java/com/facebook/flipper/plugins/databases/DatabasesFlipperPlugin.kt: (17, 5): 'onDisconnect' overrides nothing
e: /home/jitpack/build/flipperandroidnoop/src/main/java/com/facebook/flipper/plugins/databases/DatabasesFlipperPlugin.kt: (21, 5): 'runInBackground' overrides nothing

FAILURE: Build failed with an exception.
```

I think there is some mistakes with the 2 PR https://github.com/theGlenn/flipper-android-no-op/pull/13 https://github.com/theGlenn/flipper-android-no-op/pull/12. Maybe @e16din & @kobeumut can take a look?

NB: we have 2 different flipper versions declared 
`def flipper_version = '0.85.0'`
`def flipper_version = '0.87.0'`
It would be great to harmonize with the same version

**Comment by theGlenn** [comment]
Hi @julienherrero thanks reporting this, #16  should fix that issue.

**Comment by theGlenn** [comment]
https://github.com/theGlenn/flipper-android-no-op/releases/tag/0.7.0 released
