### ISSUE TITLE
0.11.1 unavailable in jitpack

### ISSUE THREAD

**Issue by afaneca** [theGlenn/flipper-android-no-op#29]
Probably related to [this jcenter issue](url).
Here's the [jitpack log](https://jitpack.io/com/github/theGlenn/flipper-android-no-op/0.11.1/build.log).

It was resolving fine this morning, but is currently unavailable.

**Comment by C2H6O** [comment]
Put up a PR: https://github.com/theGlenn/flipper-android-no-op/pull/30

**Comment by theGlenn** [comment]
Merged and fixed in #33.
Apologies for the delay.
