### ISSUE TITLE
Separate artifacts for Flipper no-op & SoLoader no-op

### ISSUE THREAD

**Issue by EricAtPlanGrid** [theGlenn/flipper-android-no-op#4]
First of all, thank you for publishing this library! I'm not sure why FB doesn't just include everything in their own no-op package, but there you go. 🙇 

I want to use this at work but I ran into an issue, which is that because we're using another FB library which also includes SoLoader, I get a build failure due to conflicting implementations. Would you be open to publishing separate artifacts? We could even keep the existing package as-is and add another:

```groovy
  // add this to no-op Flipper + SoLoader
  releaseImplementation 'com.github.theGlenn:flipper-android-no-op:0.3.0'

  // add this to no-op only Flipper
  releaseImplementation 'com.github.theGlenn:flipper-only-android-no-op:0.3.0'
```

**Comment by theGlenn** [comment]
Hi @EricAtPlanGrid yes of course it actually more sense, I can also add `'com.github.theGlenn:flipper-only-android-no-op:0.3.0'` as depndency of `'com.github.theGlenn:flipper-android-no-op:0.3.0'` then you'll be able to exclude soloader transitive dependency.

**Comment by EricAtPlanGrid** [comment]
👍 that would be fantastic!
