### ISSUE TITLE
Publish new artifact(s) with separate SoLoader no-op

### ISSUE THREAD

**Issue by EricAtPlanGrid** [theGlenn/flipper-android-no-op#8]
Hi! Thanks again for merging #5 … could you please publish a new version soon so I can start using this? 🙏

**Comment by ritwik-shanker** [comment]
@theGlenn Can we have a new version please? I really wanna use this!  🙏

**Comment by theGlenn** [comment]
@EricAtPlanGrid @ritwik-shanker I'm very sorry for the delay, I will try and be more reactive in the future

The new artifact is published you can now use it like this:
```gradle
    releaseImplementation 'com.github.theGlenn.flipper-android-no-op:flipperandroidnoop:0.4.0'
    releaseImplementation 'com.github.theGlenn.flipper-android-no-op:soloadernoop:0.4.0'
```
